/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcmph_CMPH */

#ifndef _Included_jcmph_CMPH
#define _Included_jcmph_CMPH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jcmph_CMPH
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jcmph_CMPH_init
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
